name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - ".github/workflows/deploy-backend.yml"

  workflow_dispatch:

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: ${{ vars.AWS_ROLE_ARN }}
  BACKEND_ECR_REPOSITORY: ${{ vars.BACKEND_ECR_REPOSITORY }}
  BACKEND_ASG_NAME: ${{ vars.BACKEND_ASG_NAME }}

jobs:
  deploy-backend:
    name: Build, Push, and Refresh Backend ASG
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        id: vars
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build backend image
        run: |
          docker build \
            -t $BACKEND_ECR_REPOSITORY:latest \
            -t $BACKEND_ECR_REPOSITORY:${{ steps.vars.outputs.SHORT_SHA }} \
            ./server

      - name: Push backend image to ECR
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          ECR_REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

          docker tag $BACKEND_ECR_REPOSITORY:latest $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:latest
          docker tag $BACKEND_ECR_REPOSITORY:${{ steps.vars.outputs.SHORT_SHA }} $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:${{ steps.vars.outputs.SHORT_SHA }}

          docker push $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$BACKEND_ECR_REPOSITORY:${{ steps.vars.outputs.SHORT_SHA }}

      - name: Refresh backend ASG
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name "$BACKEND_ASG_NAME" \
            --preferences MinHealthyPercentage=50,InstanceWarmup=300